import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";

type ParameterViewerProps = {
  title: string;
  subtitle: string;
  paramJson: string | undefined;
};

export default function ParameterViewer({
  title,
  subtitle,
  paramJson,
}: ParameterViewerProps) {
  const params = paramJson ? JSON.parse(paramJson) : undefined;

  return <Card className="w-1/2 shadow-none">
    <CardHeader className="bg-sidebar border-b-2 ">
      <CardTitle>
        {title}
      </CardTitle>
      <CardDescription>
        {subtitle}
      </CardDescription>
    </CardHeader>
    <CardContent className="p-0 py-3 px-5 flex flex-col justify-center items-start w-full">
      {params && Object.keys(params).length === 0 && <p className="text-sm text-muted-foreground">No parameters generated by this phase</p>}
      {params && Object.entries(params).map(([key, value]) => (
        <div key={key} className="flex w-full items-center py-1">
          <p className="text-sm text-muted-foreground flex-1 basis-1/3"> {key}</p>
          <Input readOnly value={value as string} className="flex-1 basis-2/3" />
        </div>
      ))}
    </CardContent>
  </Card >;
}
